/**
 * ===========================================
 * HOMEPAGE - AFEKA HIKING TRAILS 2026
 * ===========================================
 * 
 * This is the main landing page of the application.
 * 
 * DEFENSE NOTES:
 * 
 * WHY IS THIS A SERVER COMPONENT?
 * - No "use client" directive = Server Component by default
 * - Benefits: No JavaScript sent to client, faster initial load
 * - This page is mostly static content
 * 
 * PROJECT REQUIREMENT:
 * "Homepage bearing the title – Afeka Hiking Trails 2026"
 * "Homepage name - index.html (handled automatically by Next.js)"
 */

import Link from "next/link";

// ===========================================
// HOMEPAGE COMPONENT
// ===========================================

export default function HomePage() {
  return (
    <div className="min-h-screen">
      {/* ===========================================
          HERO SECTION
          =========================================== */}
      <section className="relative bg-gradient-to-br from-primary to-primary-dark text-white py-24 px-4">
        {/* Background Pattern */}
        <div className="absolute inset-0 opacity-10">
          <svg className="w-full h-full" viewBox="0 0 100 100" preserveAspectRatio="none">
            <path d="M0,50 Q25,20 50,50 T100,50 V100 H0 Z" fill="currentColor" />
          </svg>
        </div>

        <div className="relative max-w-7xl mx-auto text-center">
          {/* Main Title - PROJECT REQUIREMENT */}
          <h1 className="text-4xl md:text-6xl font-bold mb-6">
            Afeka Hiking Trails 2026
          </h1>
          
          <p className="text-xl md:text-2xl mb-8 max-w-3xl mx-auto opacity-90">
            Plan your perfect hiking or cycling adventure with AI-powered route suggestions,
            real-time weather forecasts, and interactive maps.
          </p>

          {/* CTA Buttons */}
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Link
              href="/planning"
              className="btn bg-white text-primary hover:bg-gray-100 text-lg px-8 py-3 shadow-lg"
            >
              Start Planning
            </Link>
            <Link
              href="/register"
              className="btn btn-outline border-white text-white hover:bg-white hover:text-primary text-lg px-8 py-3"
            >
              Create Account
            </Link>
          </div>
        </div>
      </section>

      {/* ===========================================
          FEATURES SECTION
          =========================================== */}
      <section className="py-20 px-4 bg-gray-50 dark:bg-gray-900">
        <div className="max-w-7xl mx-auto">
          <h2 className="text-3xl font-bold text-center mb-12">
            Everything You Need for Your Adventure
          </h2>

          <div className="grid md:grid-cols-3 gap-8">
            {/* Feature 1: AI Route Planning */}
            <div className="card text-center">
              <div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mx-auto mb-4">
                <svg className="w-8 h-8 text-primary" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 20l-5.447-2.724A1 1 0 013 16.382V5.618a1 1 0 011.447-.894L9 7m0 13l6-3m-6 3V7m6 10l4.553 2.276A1 1 0 0021 18.382V7.618a1 1 0 00-.553-.894L15 4m0 13V4m0 0L9 7" />
                </svg>
              </div>
              <h3 className="text-xl font-semibold mb-2">AI-Powered Routes</h3>
              <p className="text-gray-600 dark:text-gray-400">
                Get personalized hiking and cycling routes generated by advanced AI,
                tailored to your preferences and skill level.
              </p>
            </div>

            {/* Feature 2: Interactive Maps */}
            <div className="card text-center">
              <div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mx-auto mb-4">
                <svg className="w-8 h-8 text-primary" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z" />
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 11a3 3 0 11-6 0 3 3 0 016 0z" />
                </svg>
              </div>
              <h3 className="text-xl font-semibold mb-2">Interactive Maps</h3>
              <p className="text-gray-600 dark:text-gray-400">
                Visualize your routes on beautiful, interactive maps with detailed
                waypoints and realistic path rendering.
              </p>
            </div>

            {/* Feature 3: Weather Forecast */}
            <div className="card text-center">
              <div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mx-auto mb-4">
                <svg className="w-8 h-8 text-primary" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 15a4 4 0 004 4h9a5 5 0 10-.1-9.999 5.002 5.002 0 10-9.78 2.096A4.001 4.001 0 003 15z" />
                </svg>
              </div>
              <h3 className="text-xl font-semibold mb-2">Weather Forecasts</h3>
              <p className="text-gray-600 dark:text-gray-400">
                Real-time weather data for your route locations, helping you plan
                the perfect time for your adventure.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* ===========================================
          HOW IT WORKS SECTION
          =========================================== */}
      <section className="py-20 px-4">
        <div className="max-w-7xl mx-auto">
          <h2 className="text-3xl font-bold text-center mb-12">
            How It Works
          </h2>

          <div className="grid md:grid-cols-4 gap-8">
            {/* Step 1 */}
            <div className="text-center">
              <div className="w-12 h-12 bg-primary text-white rounded-full flex items-center justify-center mx-auto mb-4 text-xl font-bold">
                1
              </div>
              <h3 className="font-semibold mb-2">Choose Location</h3>
              <p className="text-gray-600 text-sm">
                Enter your desired country, region, or city
              </p>
            </div>

            {/* Step 2 */}
            <div className="text-center">
              <div className="w-12 h-12 bg-primary text-white rounded-full flex items-center justify-center mx-auto mb-4 text-xl font-bold">
                2
              </div>
              <h3 className="font-semibold mb-2">Select Trip Type</h3>
              <p className="text-gray-600 text-sm">
                Choose between hiking (trek) or cycling
              </p>
            </div>

            {/* Step 3 */}
            <div className="text-center">
              <div className="w-12 h-12 bg-primary text-white rounded-full flex items-center justify-center mx-auto mb-4 text-xl font-bold">
                3
              </div>
              <h3 className="font-semibold mb-2">Set Duration</h3>
              <p className="text-gray-600 text-sm">
                Specify how many days your trip will be
              </p>
            </div>

            {/* Step 4 */}
            <div className="text-center">
              <div className="w-12 h-12 bg-primary text-white rounded-full flex items-center justify-center mx-auto mb-4 text-xl font-bold">
                4
              </div>
              <h3 className="font-semibold mb-2">Get Your Route</h3>
              <p className="text-gray-600 text-sm">
                Review, approve, and save your personalized route
              </p>
            </div>
          </div>

          {/* CTA */}
          <div className="text-center mt-12">
            <Link
              href="/planning"
              className="btn btn-primary text-lg px-8 py-3"
            >
              Plan Your Route Now
            </Link>
          </div>
        </div>
      </section>

      {/* ===========================================
          TRIP TYPES SECTION
          =========================================== */}
      <section className="py-20 px-4 bg-gray-50 dark:bg-gray-900">
        <div className="max-w-7xl mx-auto">
          <h2 className="text-3xl font-bold text-center mb-12">
            Choose Your Adventure
          </h2>

          <div className="grid md:grid-cols-2 gap-8">
            {/* Hiking Card */}
            <div className="card hover:shadow-lg transition-shadow">
              <div className="flex items-start space-x-4">
                <div className="w-16 h-16 bg-green-100 rounded-lg flex items-center justify-center flex-shrink-0">
                  <svg className="w-10 h-10 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
                  </svg>
                </div>
                <div>
                  <h3 className="text-xl font-semibold mb-2">Hiking (Trek)</h3>
                  <ul className="text-gray-600 space-y-1 text-sm">
                    <li>• Distance: 5-10 km per day</li>
                    <li>• 1-3 circular routes</li>
                    <li>• Start and end at the same point</li>
                    <li>• Perfect for day trips</li>
                  </ul>
                </div>
              </div>
            </div>

            {/* Cycling Card */}
            <div className="card hover:shadow-lg transition-shadow">
              <div className="flex items-start space-x-4">
                <div className="w-16 h-16 bg-blue-100 rounded-lg flex items-center justify-center flex-shrink-0">
                  <svg className="w-10 h-10 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <circle cx="5.5" cy="17.5" r="3.5" strokeWidth={2} />
                    <circle cx="18.5" cy="17.5" r="3.5" strokeWidth={2} />
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 6l-3.5 4.5L8 8l-2.5 5M15 6h3m-3 0l3.5 7" />
                  </svg>
                </div>
                <div>
                  <h3 className="text-xl font-semibold mb-2">Cycling</h3>
                  <ul className="text-gray-600 space-y-1 text-sm">
                    <li>• Distance: 30-70 km per day</li>
                    <li>• Continuous city-to-city routes</li>
                    <li>• Multi-day adventures</li>
                    <li>• Explore more terrain</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}
